config/routes.rb
RailsStore::Application.routes.draw do
resources :reviews, :only => [:new, :create] 
resources :products #you can tell your resources to only use a certain set of routes
root :to => 'products#index'

get '/reviews', :controller => 'reviews', :action => 'new', :as => 'new_review'
post '/reviews(.:format)', :controller => 'reviews', :action => 'create', :as => 'review'
get '/reviews/:id(.:format)', :controller => 'reviews', :action => 'show', :as => 'review'
get '/reviews/:id/new', :controller => 'reviews', :action => 'new', :as => 'new_review'
get '/reviews/:id/edit(.:format)', :to => 'products#edit'

get 'product/cart(.:format)', :to => 'products#carted_products'
get '/yourcart', :to => 'products#carted_products'

end

app/models/product.rb
require 'open-uri'
require 'uri'

class Product < ActiveRecord::Base
  attr_accessible :name, :price, :reviews, :body, :in_cart, :image
  has_many :reviews

validates_uniqueness_of :name, :message => "This product name has been taken."
validates_presence_of :name, :message => "No product name entered."
validates_presence_of :price, :message => "Must enter price."
end

app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :body, :product_id, :rating, :product
  belongs_to :product 

  validates_length_of :body, :minimum => 50, :maximum => 1000, :message => "Review must be between 50 and 1000 characters." 
  validates_inclusion_of :rating, :in => 0..5, 
  :message => "Rating must be of values 0-5, 0 being the lowest, 5 being the highest."
end
 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  before_filter :carted_products
  
  # GET /yourcart
  # GET /yourcart.json
  def carted_products
    @carted_products = Product.where(:in_cart => true)
    # @subtotal = @carted_products.collect(params[:price])
  end


  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    @carted_products = Product.where(:in_cart => true)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # def add_to_cart 
  #   id = params[:id]
  #   @product = Product.find id
  #   @product.in_cart = true
  #   @product.save

  #   @product.update_attributes({:in_cart => true})
  # end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format| #respond_to is a method that looks inside the params hash that exposes format
      #passing the format into this block -> when the format is HTML, blah blah, when JSON, blah blahh
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reviews }
    end
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
    @review = Review.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @review }
    end
  end

  # GET /reviews/new
  # GET /reviews/new.json
  def new
    @review = Review.new  
    if params[:product_id] != nil
      @products = Product.all
      @product = Product.find(params[:product_id])
    end
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @review }
    end
  end

  # GET /reviews/1/edit
  def edit
    @review = Review.find(params[:id])
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(params[:review])
    
    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render json: @review, status: :created, location: @review }
      else
        format.html { render action: "new" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reviews/1
  # PUT /reviews/1.json
  def update
    @review = Review.find(params[:id])

    respond_to do |format|
      if @review.update_attributes(params[:review])
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review = Review.find(params[:id])
    @review.destroy

    respond_to do |format|
      format.html { redirect_to reviews_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <img src="store.png" alt="this is an alt tag"/>
  <title>TinyStore</title>
  <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-combined.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <h1> Welcome to TinyStore <h1>
      <div class="navbar">
        <div class="navbar-inner">
          <a class="brand" href="/">TinyStore</a>
      <ul class="nav">
        <li class="active" title="link to home"><a href='/'>Home</a></li>
        <li class="active" title="link to products"><a href='/products'>Products</a></li>
        <li class="active" title="link to cart"><a href='/yourcart'>Checkout</a></li>
      </ul>
    </div>
  </div>
</div>
<img src="logo.png" alt="this is an alt tag"/>
<%= yield %>

</body>
</html>

app/views/layouts/test.html.erb
<img src="logo.png"/> 

<input type="text"></input>  

app/views/products/_add_to_cart.html.erb
<%= form_for(@product) do |f| %>
  <div class="cart">
    <% if @product.in_cart == false %>
    <%= f.hidden_field :in_cart, :value => true %><br />
      <%= f.submit "Add to Cart." %>
    <% else %>
      <%= f.hidden_field :in_cart, :value => false %><br />
      <%= f.submit "Remove from Cart." %>
    <% end %>
  </div>
<% end %>

app/views/products/_cart.html.erb
<div class="cart_page">
  <table>
    <% sum = 0 %>
  <% @carted_products.each do |product| %>
<tr>
  <td><%= product.name %></td>
  <td><%= number_to_currency(product.price) %></td>
</tr>
<% end %>
<table>
  
</div>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/carted_products.html.erb
<div class="cart_page">
  <h2> TinyStore Current Cart Items </h2>
    <table>
      <% @carted_products.each do |product| %>
        <tr>
          <td><%= product.name %></td>
          <td><%= number_to_currency(product.price) %></td>
        </tr>
      <% end %>
    </table>
</div>
<button>Checkout</button>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="subheadings">
  <h1>TinyStore's Newest Products</h1>
</div>

<table class="table"> 
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th>Buy</th>
    <th>Edit</th>
    <th>Remove</th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= number_to_currency(product.price) %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<br />
<h2> Your Cart <h2>
<%= render 'cart' %>

<div class="links">

<%= link_to 'New Product', new_product_path %>
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/new_reviews.html.erb
<%= form_for @review do |f| %>
  <% if @review && @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.text_field :rating %>
  </div>
  <div class="field">
    <% if @product %>
    <input type="hidden" name="review[product_id]" value="<%= @product.id %>">
    <% else %>
      <%= f.label :product_id %><br />
      <%= f.number_field :product_id %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Price:</b>
  <%= number_to_currency(@product.price) %>
</p>
<p>
</p>

<h2> Your Cart <h2>
<%= render 'cart' %>
<p> 
</p>

<p>
<h2> Reviews for <%= @product.name %> </h2>
 <table> 
    <tr>
    <th> Review Body </th>
    <th> Product Rating </th>
    </tr>
  <% @product.reviews.each do |review| %>
  <tr>
    <td><%= review.body %></td>
    <td><%= review.rating %> </td>
  </tr>
  <% end %>
</table>
<p>
  <b><a class="btn btn-primary" href="/reviews?product_id=<%= @product[:id] %>/new"><i class= "icon-pencil icon-white"></i> Write Review</a></b>
<p>

<%= render 'add_to_cart' %>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.text_field :rating %>
  </div>
  <div class="field">
    <% if @product %>
    <input type="hidden" name="review[product_id]" value="<%= @product.id %>">
    <% else %>
      <%= f.label :product_id %><br />
      <%= f.number_field :product_id %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>
<%= image_tag "img.png %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<h1>Listing reviews</h1>

<table>
  <tr>
    <th>Body</th>
    <th>Rating</th>
    <th>Product</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reviews.each do |review| %>
  <tr>
    <td><%= review.body %></td>
    <td><%= review.rating %></td>
    <td><%= review.product_id %></td>
    <td><%= link_to 'Show', review %></td>
    <td><%= link_to 'Edit', edit_review_path(review) %></td>
    <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<% if @product %>
<h1>New Review For <%= @product.name %> </h1>
<% else %>
<h1> New Review </h1>
<% end %>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <b>Product:</b>
  <%= @review.product_id %>
</p>

<p>
  <b>Rating:</b>
  <%= @review.rating %>
</p>


<p>
  <b>Body:</b>
  <%= @review.body %>
</p>

<%= params.inspect %>


<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back to Home', products_path %>